name: vispr-online
channels:
- defaults
dependencies:
  - python==3.5.1
  - click
  - Flask
  - itsdangerous
  - Jinja2
  - MarkupSafe
  - numpy
  - pandas==0.19.1
  - pymongo
  - python-dateutil
  - pytz
  - PyYAML
  - scikit-learn
  - scipy
  - six
  - Werkzeug